# yaml-language-server: $schema=./config_schema.json

name: "Example Configuration"

cloud_profiles:
  - name: "Personal"
    connections:
      - type: "aws"
        value:
          access_key_id: "AKIAIOSFODNN7EXAMPLE"
          secret_access_key: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
  - name: "Work - Internal"
    connections:
      - type: "aws"
        value:
          access_key_id: "AKIAIOSFODH7EXAMPLE"
          secret_access_key: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
  - name: "Work - Client"
    connections:
      - type: "do"
        value:
          token: "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"
      - type: "hetzner"
        value:
          token: "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"
