name: clompse
version: 0.0.1
github: vst/clompse
license: MIT
author: Vehbi Sinan Tunalioglu
maintainer: vst@vsthost.com
copyright: Copyright (c) 2024 Vehbi Sinan Tunalioglu
extra-source-files:
  - README.md
  - CHANGELOG.md
description: Please see the README on GitHub at <https://github.com/vst/clompse#readme>
dependencies:
  - base >= 4.7 && < 5
library:
  source-dirs: src
  ghc-options:
    - '-Wall'
    - '-Werror'
    - '-Wunused-packages'
  dependencies:
    - aeson
    - amazonka
    - amazonka-core
    - amazonka-ec2
    - amazonka-lightsail
    - async-pool
    - autodocodec
    - autodocodec-schema
    - bytestring
    - cassava
    - conduit
    - format-numbers
    - githash
    - hetzner
    - ip
    - lens
    - mtl
    - optparse-applicative
    - scientific
    - string-interpolate
    - table-layout
    - template-haskell
    - text
    - time
    - typed-process
    - unordered-containers
    - vector
    - yaml

executables:
  clompse:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - '-Wall'
      - '-Werror'
      - '-Wunused-packages'
      - '-threaded'
      - '-rtsopts'
      - '-with-rtsopts=-N'
    dependencies:
      - clompse
tests:
  clompse-test:
    main: Spec.hs
    source-dirs: test/spec
    ghc-options:
      - '-Wall'
      - '-Werror'
      - '-Wunused-packages'
      - '-threaded'
      - '-rtsopts'
      - '-with-rtsopts=-N'
    dependencies: []
  clompse-doctest:
    main: doctest.hs
    source-dirs: test/doctest
    ghc-options:
      - '-Wall'
      - '-Werror'
      - '-threaded'
    dependencies:
      - clompse
      - doctest
