## This resolver should correspond to our nixpkgs version (at least baseline):
resolver: lts-24.25

## Our local packages:
packages:
  - .

## Use the GHC provided by our Docker build image; never download another one:
system-ghc: true
install-ghc: false

## Allow running as a different user inside Docker containers:
allow-different-user: true

## Set the output path for our compiled binaries (stack install):
local-bin-path: /tmp

## Configure Cabal to build static executables (no shared/dynamic):
configure-options:
  "$locals":
    - --disable-shared
    - --disable-executable-dynamic
    - --enable-executable-static

## Make smaller libs without any profiling:
build:
  library-profiling: false
  library-stripping: true

## Extra dependencies pinned to specific commits:
extra-deps:
  - github: brendanhay/amazonka
    commit: a7d699be1076e2aad05a1930ca3937ffea954ad8
    subdirs:
      - lib/amazonka
      - lib/amazonka-core
      - lib/services/amazonka-ec2
      - lib/services/amazonka-lightsail
      - lib/services/amazonka-route53
      - lib/services/amazonka-s3
      - lib/services/amazonka-sso
      - lib/services/amazonka-sts
  - github: stevenfontanella/microlens
    commit: a8d75ac12735e5d9962b51822dbcd0f2103267f3
    subdirs:
      - microlens-pro
